### ISSUE TITLE
The extension is not working anymore

### ISSUE THREAD

**Issue by ghost** [vatz88/Pluralsight-Course-Downloader#10]
Hey,

Starting from today I can't download the video no more.
Is only me or other people have the same problem ? 

Thanks for your work.
Filippo

**Comment by oldhatgaming** [comment]
Mine isn't working because of this: 
```js
var saveFileName = fileIndex + ' - ' + rawFileName + '.' + link.split('?')[0].split('.').pop();
```
Does this address the issue?

**Comment by vatz88** [comment]
@secretclean That line of code is the same. Make sure you are using the latest code. If the issue still persists, create a new issue and add the error you are getting.

**Comment by jadedevin13** [comment]
I agree with @secretclean, the link was updated again.

A work around is to change line 14 to

```js
var link = $('#vjs_video_355_html5_api');
```
