### ISSUE TITLE
Sequencial downloads

### ISSUE THREAD

**Issue by da-musaddiq** [vatz88/Pluralsight-Course-Downloader#11]
my internet speed is not always able to keep up with the download interval timing when using the 'a' option and it causes all previous videos to stop downloading and even corrupt. Rather than using download interval timing (30 seconds by default) i think a sequential download feature will be more functional where the next download wont start until the previous one is completed. Thanks. Very nice job anyways

**Comment by vatz88** [comment]
Fixed in #14
