### ISSUE TITLE
renaming to 1280x720

### ISSUE THREAD

**Issue by dkoryto** [vatz88/Pluralsight-Course-Downloader#12]
For some reason my extension isn't automatically renaming the files and sorting them into their proper file structures. After the first file downloaded and was named properly, the other files downloaded all as "1280x720.mp4".

Communicator with an error:

Error in background.js
Unchecked runtime.lastError while running downloadsInternal.determineFilename: Invalid filename
background.js:24

**Comment by vatz88** [comment]
`filename` determined seems to be invalid. Maybe, if you can, put a log and see what the file name is being passed on. Is it happening for all courses or some specific course?

**Comment by dkoryto** [comment]
The problem sometimes appears in specific courses.

**Comment by rozarlive** [comment]
The issue is with sometimes with the names having trailing spaces for directories
Typical setup is CourseName/FolderName/FileName

The error occurs when you come across the case: CourseName/FolderName /FileName. 

The FolderName with a trailing space will throw an error and the solution is to trim.

` return 'Pluralsight/' + courseName + '/' + saveFolder.trim() + '/' + saveFileName;`

**Comment by rozarlive** [comment]
The issue happens with the directory names having trailing spaces
Typical setup is CourseName/FolderName/FileName

The error occurs when you come across the case: CourseName/FolderName /FileName.

The FolderName with a trailing space will throw an error and the solution is to trim.

return 'Pluralsight/' + courseName + '/' + saveFolder.trim() + '/' + saveFileName;

**Comment by vatz88** [comment]
Thanks @rozarlive !

I would appreciate if you or anyone else could make a PR with the fix :)

**Comment by tejasgarde** [comment]
Hi @vatz88 I have submitted a pull Request that fixes this bug can you please check and merge the same
The solution is to remove the 'new line' (\r \n )from the File path. I have tested the code and its working fine.
Thanks a lot for such wonderful extension.
