### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by ArjonBu** [vatz88/Pluralsight-Course-Downloader#2]
Hi, 
The extension is not working today. It downloads the files with the name 1280x720.mp4 and no organizing in folders with proper names.

**Comment by vatz88** [comment]
Hi, I just checked it and it's working for me. Can you tell me for which video it's not working for you?

**Comment by ArjonBu** [comment]
There were a couple of videos that were downloaded that way but later it returned back to working. 

BTW could you add automatic downloading? For example, we could specify the time to move automatically to the next video and download it.

**Comment by vatz88** [comment]
Well yeah, that can be a feature. Created #3 for that. If anyone interested can take it up or I'll see when I get time.
