### ISSUE TITLE
Automatic Download

### ISSUE THREAD

**Issue by vatz88** [vatz88/Pluralsight-Course-Downloader#3]
Add option to download video automatically without pressing the `s` key.

**Comment by ArjonBu** [comment]
I think this is the most important feature for a downloader. No one has the time to stay manually through every video to download it with "s", wait 20-30 seconds, then move to the next video and repeat the process. 
I would appreciate this feature.

**Comment by richie777cfc** [comment]
@Arjoni Check my [fork](https://github.com/richie777cfc/Pluralsight-Course-Downloader). I have added this feature. 😄

**Comment by vatz88** [comment]
@richie777cfc why don't you make a PR so that everyone can get the feature!

**Comment by richie777cfc** [comment]
@vatz88 Done!

**Comment by ArjonBu** [comment]
@richie777cfc does it download subtitles?

**Comment by richie777cfc** [comment]
@Arjoni subtitles support not yet added. Will check on it.

**Comment by vatz88** [comment]
feature added with #5
