### ISSUE TITLE
Video paths not populated when downloading

### ISSUE THREAD

**Issue by oldhatgaming** [vatz88/Pluralsight-Course-Downloader#7]
Hey, for some reason my extension isn't automatically renaming the files and sorting them into their proper file structures. After the first file downloaded and was named properly, the other 29 files downloaded all as "1280x720." Not sure why, since the code looks good and worked in populating the fileIndex and rawFileName/saveFileName for the first one. It's grabbing the names from #module-clip-title which is also right. Is this some PluralSight thing where they mess up the div id when you're in a playlist? What would make it not work properly?

**Comment by vatz88** [comment]
Hi @secretclean 

Not sure why this is happening. If Pluralsight has updated it's site, then it'll not work for everyone. If it's just you, try putting more `console.log()` statements in code to check where the correct file name is getting missed. Also, try with different courses.

**Comment by oldhatgaming** [comment]
I think it might have to do with the basic trial account being limited to 200 minutes. Perhaps there is some server-side logging invalidating sequential enumeration and preventing the title from being passed through. I signed up for a full account and have no problems with it now. Script is awesome, thanks for sharing it!
